### ISSUE TITLE
why in RNN, the linear layer's input size is 4 * hidden_size? 

### ISSUE THREAD

**Issue by Yue1Harriet1** [prakashpandey9/Text-Classification-Pytorch#7]
If it is because that it is a bi-RNN, then shouldn't it be 2 times the hidden_size only?

Thanks

**Comment by quanghuynguyen1902** [comment]
me too. I don't know the linear layer's input size is 4* hidden_size

**Comment by prakashpandey9** [comment]
It's because the network is bidirectional & there are 2 such RNN layers. So 2*2*hidden_size is the input size of the linear layer. Hope this helps.
